services:
  postgres:
    image: postgres:15
    container_name: pet-app-postgres
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: petapp
      POSTGRES_PASSWORD: petapp123
    ports:
      - "5435:5432"
    volumes:
      - /Volumes/samsumg/docker/vol/postgres-data:/var/lib/postgresql/data
    networks:
      - pet-app-network

  pet-app:
    build: .
    container_name: pet-app
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - postgres
    environment:
      R2DBC_URL: r2dbc:postgresql://postgres:5432/local?currentSchema=petapp
#      R2DBC_URL: r2dbc:postgresql:/host.docker.internal:5435/local?currentSchema=petapp
      R2DBC_USERNAME: petapp
      R2DBC_PASSWORD: petapp123
    networks:
      - pet-app-network

networks:
  pet-app-network:
    driver: bridge